include_guard(GLOBAL)

include(CMakeParseArguments)
include(PlatformSelect)

function(app_load_platform_bootstrap source_dir platform extra_platform_dirs)
    app_get_platform_dir("${source_dir}" "${platform}" "${extra_platform_dirs}" _platform_dir)
    set(_bootstrap_script "${_platform_dir}/bootstrap.cmake")

    if(NOT EXISTS "${_bootstrap_script}")
        message(FATAL_ERROR "Missing platform bootstrap script: ${_bootstrap_script}")
    endif()

    set(APP_PLATFORM_SOURCE_DIR "${source_dir}")
    set(APP_PLATFORM_DIR "${_platform_dir}")
    include("${_bootstrap_script}")

    if(NOT COMMAND platform_bootstrap_dependencies)
        message(FATAL_ERROR "${_bootstrap_script} must define platform_bootstrap_dependencies()")
    endif()

    if(NOT COMMAND platform_bootstrap_toolchain)
        message(FATAL_ERROR "${_bootstrap_script} must define platform_bootstrap_toolchain()")
    endif()
endfunction()

function(app_bootstrap_platform_environment)
    cmake_parse_arguments(ARG "" "SOURCE_DIR;PLATFORM;CACHE_DIR;ALLOW_FETCH;OUT_CACHE_SEED" "EXTRA_PLATFORM_DIRS" ${ARGN})

    if(NOT ARG_SOURCE_DIR)
        message(FATAL_ERROR "app_bootstrap_platform_environment requires SOURCE_DIR")
    endif()

    if(NOT ARG_PLATFORM)
        message(FATAL_ERROR "app_bootstrap_platform_environment requires PLATFORM")
    endif()

    if(NOT ARG_CACHE_DIR)
        message(FATAL_ERROR "app_bootstrap_platform_environment requires CACHE_DIR")
    endif()

    app_load_platform_bootstrap("${ARG_SOURCE_DIR}" "${ARG_PLATFORM}" "${ARG_EXTRA_PLATFORM_DIRS}")

    platform_bootstrap_dependencies(
        SOURCE_DIR "${ARG_SOURCE_DIR}"
        PLATFORM "${ARG_PLATFORM}"
        CACHE_DIR "${ARG_CACHE_DIR}"
        ALLOW_FETCH "${ARG_ALLOW_FETCH}"
    )

    platform_bootstrap_toolchain(
        SOURCE_DIR "${ARG_SOURCE_DIR}"
        PLATFORM "${ARG_PLATFORM}"
        CACHE_DIR "${ARG_CACHE_DIR}"
        ALLOW_FETCH "${ARG_ALLOW_FETCH}"
    )

    set(_cache_seed "")
    if(COMMAND platform_bootstrap_cache_seed)
        platform_bootstrap_cache_seed(_cache_seed)
    endif()

    if(ARG_OUT_CACHE_SEED)
        set(${ARG_OUT_CACHE_SEED} "${_cache_seed}" PARENT_SCOPE)
    endif()
endfunction()

function(app_write_bootstrap_cache_file)
    cmake_parse_arguments(ARG "" "OUTPUT_FILE;PLATFORM" "CACHE_SEED" ${ARGN})

    if(NOT ARG_OUTPUT_FILE)
        message(FATAL_ERROR "app_write_bootstrap_cache_file requires OUTPUT_FILE")
    endif()

    get_filename_component(_output_dir "${ARG_OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_dir}")

    file(WRITE "${ARG_OUTPUT_FILE}" "# Generated by cmake/Bootstrap.cmake.\n")
    file(APPEND "${ARG_OUTPUT_FILE}" "set(APP_PLATFORM \"${ARG_PLATFORM}\" CACHE STRING \"\" FORCE)\n")

    foreach(_entry IN LISTS ARG_CACHE_SEED)
        string(REPLACE "|" ";" _parts "${_entry}")
        list(LENGTH _parts _part_count)

        if(_part_count LESS 3)
            message(FATAL_ERROR
                "Invalid cache seed entry '${_entry}'. Expected format: VARIABLE|TYPE|VALUE")
        endif()

        list(GET _parts 0 _variable)
        list(GET _parts 1 _type)
        list(GET _parts 2 _value)

        file(APPEND
            "${ARG_OUTPUT_FILE}"
            "set(${_variable} \"${_value}\" CACHE ${_type} \"\" FORCE)\n")
    endforeach()
endfunction()
